### PR TITLE
Adding Gen 8 Pokemons english only

### PR DESCRIPTION
**Pull request by alexmartz710**
Also updated README with images and Mega eggs and raids info

### CODE REVIEW

**Comment by ccev** [comment]
did you test this? from a quick look, sirfetch'd might cause issues with the ' in its name

**Comment by alexmartz710** [comment]
Yes I specifically tested Sirfetch'd and it works fine

**Comment by alexmartz710** [comment]
image

**Comment by ccev** [comment]
yeah ok. thank you

**Pull request merged**
